# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: JahnaviAgent

steps:
- task: UiPathPack@4
  inputs:
    versionType: 'CurrentVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/project.json'
    orchestratorConnection: 'AzureDevops'
    outputPath: '$(Build.ArtifactStagingDirectory)/output'
    tracelevel: 'verbose'

- task: UiPathDeploy@4
  inputs:
         orchestratorConnection: 'AzureDevops'
         PackagesPath: '$(Build.ArtifactStagingDirectory)/output'
         Createprocess: true
         folderName: 'Shared'
         tracelevel: 'verbose'

